# Generated by Django 6.0.5 on 2026-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='audio_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
