# Generated by Django 4.2.30 on 2026-05-25 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'transcription',
                'verbose_name_plural': 'transcriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
