# Generated by Django 4.2.30 on 2026-05-26 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_notes', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'structured notes',
                'verbose_name_plural': 'structured notes',
            },
        ),
    ]
