# Generated by Django 4.2.30 on 2026-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_add_structured_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurednotes',
            name='speaker_segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
