# Generated by Django 4.2 on 2026-05-27 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import integrations.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('slack', 'Slack'), ('notion', 'Notion'), ('google_calendar', 'Google Calendar')], max_length=50)),
                ('access_token', integrations.models.EncryptedTextField(help_text='Encrypted OAuth access token')),
                ('refresh_token', integrations.models.EncryptedTextField(blank=True, help_text='Encrypted OAuth refresh token (optional)', null=True)),
                ('workspace_or_channel', models.CharField(blank=True, help_text='Stores Slack channel ID or Notion workspace ID', max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Any additional data per integration')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'integration_type')},
            },
        ),
    ]
