# Generated by Django 4.2 on 2026-05-27 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_audio_file'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='meetings.meeting')),
            ],
        ),
    ]
